#:kivy 2.3.0
<ArtistCard>:
    size_hint: None, None
    size: 180, 80
    padding: 20, 10
    anchor_x: 'left'
    anchor_y: 'center'
    canvas.before:
        Color:
            rgba: 1, 1, 1, 0.5
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [40]
    Label:
        text: root.name
        size: self.texture_size
        size_hint: None, None
        font_size: 20